export const defaultChannels = [
  { id: 'la-une', name: 'La Une', group: 'French', aliases: ['LA UNE (RTBF)', 'RTBF La Une'], xmltvIds: ['LaUne.be', 'LaUne.be@SD', 'LaUne.be@HD'] },
  { id: 'tipik', name: 'Tipik', group: 'French', aliases: ['TIPIK', 'TIPIK HD'], xmltvIds: ['Tipik.be', 'Tipik.be@HD'] },
  { id: 'la-trois', name: 'La Trois', group: 'French', aliases: ['RTBF La Trois'], xmltvIds: ['LaTrois.be', 'LaTrois.be@SD'] },
  { id: 'rtl-tvi', name: 'RTL tvi', group: 'French', aliases: ['RTLTVI', 'RTL tvi HD'], xmltvIds: ['RTLTVI.be', 'RTLTVI.be@SD', 'RTLTVI.be@HD'] },
  { id: 'rtl-club', name: 'RTL club', group: 'French', aliases: ['Club RTL', 'RTL Club'], xmltvIds: ['RTLClub.be', 'ClubRTL.be'] },
  { id: 'rtl-plug', name: 'RTL plug', group: 'French', aliases: ['Plug RTL', 'RTL Plug'], xmltvIds: ['RTLPlug.be', 'PlugRTL.be'] },
  { id: 'tf1', name: 'TF1', group: 'French', aliases: ['TF1 HD'], xmltvIds: ['TF1.fr', 'TF1.fr@SD', 'TF1.fr@HD'] },
  { id: 'france-2', name: 'France 2', group: 'French', aliases: ['FRANCE 2'], xmltvIds: ['France2.fr', 'France2.fr@SD', 'France2.fr@HD'] },
  { id: 'france-3', name: 'France 3', group: 'French', aliases: ['FRANCE 3'], xmltvIds: ['France3.fr', 'France3.fr@SD', 'France3.fr@HD'] },
  { id: 'france-4', name: 'France 4', group: 'French', aliases: ['FRANCE 4'], xmltvIds: ['France4.fr', 'France4.fr@HD'] },
  { id: 'france-5', name: 'France 5', group: 'French', aliases: ['FRANCE 5'], xmltvIds: ['France5.fr', 'France5.fr@SD', 'France5.fr@HD'] },
  { id: 'arte', name: 'Arte', group: 'French', aliases: ['ARTE', 'arte HD'], xmltvIds: ['arte.fr', 'arte.fr@SD', 'arte.fr@HD'] },
  { id: 'tv5-monde', name: 'TV5 Monde', group: 'French', aliases: ['TV5 MONDE'], xmltvIds: ['TV5MondeFranceBelgiumSwitzerlandMonaco.fr'] },
  { id: 'tmc', name: 'TMC', group: 'French', aliases: ['TMC HD'], xmltvIds: ['TMC.fr', 'TMC.fr@SD'] },
  { id: 'ab3', name: 'AB3', group: 'French', aliases: ['AB3 HD'], xmltvIds: ['AB3.be', 'AB3.be@SD', 'AB3.be@HD'] },
  { id: 'abxplore', name: 'ABXplore', group: 'French', aliases: ['ABXPLO HD'], xmltvIds: ['ABXplore.be', 'ABXplore.be@HD'] },
  { id: 'vrt-1', name: 'VRT 1', group: 'Dutch', aliases: ['VRT1', 'Eén'], xmltvIds: ['VRT1.be', 'VRT1.be@SD', 'VRT1.be@HD'] },
  { id: 'vrt-canvas', name: 'VRT Canvas', group: 'Dutch', aliases: ['Canvas', 'VRT CANVAS'], xmltvIds: ['VRTCanvas.be', 'VRTCanvas.be@SD', 'Canvas.be'] },
  { id: 'ketnet', name: 'Ketnet', group: 'Dutch', aliases: ['KETNET'], xmltvIds: ['Ketnet.be', 'Ketnet.be@SD', 'Ketnet.be@HD'] },
  { id: 'vtm', name: 'VTM', group: 'Dutch', aliases: ['VTM HD'], xmltvIds: ['VTM.be', 'VTM.be@SD', 'VTM.be@HD'] },
  { id: 'vtm-2', name: 'VTM 2', group: 'Dutch', aliases: ['VTM2'], xmltvIds: ['VTM2.be', 'VTM2.be@SD', 'VTM2.be@HD'] },
  { id: 'vtm-3', name: 'VTM 3', group: 'Dutch', aliases: ['VTM3'], xmltvIds: ['VTM3.be', 'VTM3.be@SD', 'VTM3.be@HD'] },
  { id: 'vtm-4', name: 'VTM 4', group: 'Dutch', aliases: ['VTM4'], xmltvIds: ['VTM4.be', 'VTM4.be@SD'] },
  { id: 'vtm-gold', name: 'VTM Gold', group: 'Dutch', aliases: ['VTMGold'], xmltvIds: ['VTMGold.be', 'VTMGold.be@SD'] },
  { id: 'play-4', name: 'Play4', group: 'Dutch', aliases: ['VIER', 'Play 4'], xmltvIds: ['Play4.be', 'Play4.be@SD', 'Play4.be@HD'] },
  { id: 'play-5', name: 'Play5', group: 'Dutch', aliases: ['VIJF', 'Play 5'], xmltvIds: ['Play5.be', 'Play5.be@SD', 'Play5.be@HD'] },
  { id: 'play-6', name: 'Play6', group: 'Dutch', aliases: ['ZES', 'Play 6'], xmltvIds: ['Play6.be', 'Play6.be@SD', 'Play6.be@HD'] },
  { id: 'play-7', name: 'Play7', group: 'Dutch', aliases: ['Play 7'], xmltvIds: ['Play7.be', 'Play7.be@SD'] },
  { id: 'npo-1', name: 'NPO 1', group: 'Dutch', aliases: ['NPO1'], xmltvIds: ['NPO1.nl', 'NPO1.nl@SD', 'NPO1.nl@HD'] },
  { id: 'npo-2', name: 'NPO 2', group: 'Dutch', aliases: ['NPO2'], xmltvIds: ['NPO2.nl', 'NPO2.nl@SD', 'NPO2.nl@HD'] },
  { id: 'npo-3', name: 'NPO 3', group: 'Dutch', aliases: ['NPO3'], xmltvIds: ['NPO3.nl', 'NPO3.nl@SD', 'NPO3.nl@HD'] },
  { id: 'nat-geo', name: 'National Geographic', group: 'Documentary', aliases: ['Nat Geo', 'NATIONAL GEOGRAPHIC CHANNEL'], xmltvIds: ['NationalGeographic.fr', 'NationalGeographic.nl', 'NationalGeographic.fr@SD'] },
  { id: 'nat-geo-wild', name: 'Nat Geo Wild', group: 'Documentary', aliases: ['NGC Wild', 'National Geographic Wild'], xmltvIds: ['NationalGeographicWild.fr', 'NationalGeographicWild.nl'] },
  { id: 'discovery', name: 'Discovery Channel', group: 'Documentary', aliases: ['Discovery'], xmltvIds: ['DiscoveryChannel.be', 'DiscoveryChannel.fr', 'DiscoveryChannel.nl'] },
  { id: 'animal-planet', name: 'Animal Planet', group: 'Documentary', aliases: ['Animal Pl'], xmltvIds: ['AnimalPlanet.nl', 'AnimalPlanet.nl@HD'] },
  { id: 'disney-channel', name: 'Disney Channel', group: 'Kids', aliases: ['DISNEY CHANNEL'], xmltvIds: ['DisneyChannel.fr', 'DisneyChannel.fr@SD'] },
  { id: 'nickelodeon', name: 'Nickelodeon', group: 'Kids', aliases: ['nick N HD'], xmltvIds: ['Nickelodeon.nl', 'Nickelodeon.nl@HD'] },
  { id: 'cartoon-network', name: 'Cartoon Network', group: 'Kids', aliases: ['CARTOON NETWORK'], xmltvIds: ['CartoonNetworkCEE.uk', 'CartoonNetworkCEE.uk@France'] },
  { id: 'boomerang', name: 'Boomerang', group: 'Kids', aliases: ['BOOMERANG'], xmltvIds: ['Boomerang.fr', 'Boomerang.fr@SD'] },
  { id: 'eurosport-1', name: 'Eurosport 1', group: 'Sport', aliases: ['EUROSPORT'], xmltvIds: ['Eurosport1.fr', 'Eurosport1.fr@France'] },
  { id: 'eurosport-2', name: 'Eurosport 2', group: 'Sport', aliases: ['EUROSPORT 2'], xmltvIds: ['Eurosport2.fr'] },
  { id: 'ln24', name: 'LN24', group: 'News', aliases: ['LN24 HD'], xmltvIds: ['LN24.be', 'LN24.be@SD'] },
  { id: 'lci', name: 'LCI', group: 'News', aliases: ['LCI HD'], xmltvIds: ['LCI.fr', 'LCI.fr@SD'] },
  { id: 'euronews', name: 'Euronews', group: 'News', aliases: ['Euronews F', 'Euronews EN'], xmltvIds: ['EuronewsFrench.fr', 'EuronewsEnglish.fr'] },
  { id: 'bbc-news', name: 'BBC World News', group: 'News', aliases: ['BBC News'], xmltvIds: ['BBCNews.uk', 'BBCWorldNews.uk'] },
  { id: 'cnn', name: 'CNN International', group: 'News', aliases: ['CNN'], xmltvIds: ['CNNInternational.us', 'CNNInternationalEurope.us'] },
  { id: 'al-jazeera', name: 'Al Jazeera English', group: 'News', aliases: ['Al Jazeera Eng'], xmltvIds: ['AlJazeeraEnglish.qa'] },
  { id: 'das-erste', name: 'Das Erste', group: 'International', aliases: ['ARD'], xmltvIds: ['DasErste.de', 'DasErste.de@SD'] },
  { id: 'zdf', name: 'ZDF', group: 'International', aliases: ['ZDF HD'], xmltvIds: ['ZDF.de', 'ZDF.de@SD'] },
  { id: 'bbc-one', name: 'BBC One', group: 'International', aliases: ['BBC1'], xmltvIds: ['BBCOne.uk'] },
  { id: 'bbc-two', name: 'BBC Two', group: 'International', aliases: ['BBC2'], xmltvIds: ['BBCTwo.uk'] },
  { id: 'bbc-first', name: 'BBC First', group: 'International', aliases: ['BBC First'], xmltvIds: ['BBCFirst.uk', 'BBCFirst.uk@Benelux'] },
  { id: 'mtv', name: 'MTV', group: 'Music', aliases: ['MTV Europe'], xmltvIds: ['MTV.fr', 'MTV.fr@SD'] },
  { id: 'trace-urban', name: 'Trace Urban', group: 'Music', aliases: ['TRACE URBAN'], xmltvIds: ['TraceUrban.fr'] },
  { id: 'mezzo', name: 'Mezzo', group: 'Music', aliases: ['MEZZO'], xmltvIds: ['Mezzo.fr', 'Mezzo.fr@SD'] },
  { id: 'kanaal-z', name: 'Kanaal Z', group: 'Business', aliases: ['KanaalZ'], xmltvIds: ['KanaalZ.be', 'KanaalZ.be@HD'] },
  { id: 'njam', name: 'Njam!', group: 'Lifestyle', aliases: ['Njam'], xmltvIds: ['Njam.be', 'Njam.be@SD', 'Njam.be@HD'] },
  { id: 'dobbit', name: 'Dobbit TV', group: 'Lifestyle', aliases: ['Dobbit'], xmltvIds: ['DobbitTV.be', 'DobbitTV.be@NL'] },
  { id: 'plattelands', name: 'PlattelandsTV', group: 'Lifestyle', aliases: ['Plattelands'], xmltvIds: ['PlattelandsTV.be', 'PlattelandsTV.be@SD'] }
]
